# Generated by Django 5.0.4 on 2024-04-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
