# Generated by Django 5.0.4 on 2024-04-16 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
        ('shows_application', '0002_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication_app.user'),
            preserve_default=False,
        ),
    ]
