# Generated by Django 5.0.4 on 2024-04-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_application', '0003_show_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='show_comments',
            field=models.ManyToManyField(to='shows_application.show'),
        ),
    ]
