# Generated by Django 5.0.4 on 2024-04-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_application', '0004_alter_comments_show_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='comments',
            field=models.TextField(default='add some notes for the show'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='show_comments',
            field=models.ManyToManyField(related_name='show_comments', to='shows_application.show'),
        ),
    ]
